# Numpy
### Used for numerical computing
Since Python is slow -> we use NumpPy, it uses C programming behind the scenes
So NumPy 



In [6]:
#np is a shorter nickname for numpy
import numpy as np  
# create a python list
my_list = [1, 2, 3, 4]
print(my_list)
my_list = my_list * 2
print(my_list)
# the difference between a list and a numpy array isthat the python list will repeat the list when multiplied by 2, while the numpy array will multiply each element by 2.
# create a np array 
array = np.array([1, 2, 3, 4])
print(array)
array = array * 2
print(array)







[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]
[1 2 3 4]
[2 4 6 8]


## Multidimensional arrays

In [ ]:
# 0d array, it is like a single number or point, it has no dimensions
array_0d = np.array(1)
print(array_0d.ndim)
# 1d array
array_1d = np.array([1, 2, 3, 4])
print(array_1d.ndim)
# 2d array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim)
# 3d array
array_3d = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(array_3d.ndim)    

# we need a consistent number of elements in each row to create a 2d array, 
# if we have a different number of elements in each row, we will get an error.

# previously with Python list we would access elements like this: print(my_list[0][0][0] this is called chain indexing,
# but with numpy array we can access elements like this: print(array_3d[0, 0, 0]) this is called multi-dimensional indexing that is faster than chain indexing.

# concatenating
number = array_3d[0,0,0] + array_3d[0,0,1] + array_3d[0,0,2] # 1+2+3
print(number)

0
1
2
3
6


## Slicing 

In [35]:
# 2d array

array = np.array([  [1, 2, 3, 4], 
                    [5, 6, 7, 8], 
                    [9, 10, 11, 12], 
                    [13, 14, 15, 16]])
# row selection
# array[start:end:step] , ending index is exclusive, step is optional
print(array[2]) # going to give the third row ( index 2 )
print(array[1:3]) # going to give second ( index 1 ) and third row ( index 2 )
print(array[0:]) # going to give all the rows starting from the first row ( index 0 ) to the end of the array
print(array[0:4:2]) # going to give the first and third row ( index 0 and index 2 ) because we are stepping by 2
# column selection
print(array[:, 0]) # going to give the first column ( index 0 ) of all the rows ( : )
print(array[:, 1:3]) # going to give the second and third column ( index 1 and index 2 ) of all the rows ( : )
print(array[:, 0:]) # going to give all the columns starting from the first column ( index 0 ) to the end of the array for all the rows ( : )
print(array[:, 0:4:2]) # going to give the first and third column ( index 0 and index 2 ) of all the rows ( : ) because we are stepping by 2
# subarray selection
print(array[0:2, 0:2]) # going to give the first and second row ( index 0 and index 1 ) and the first and second column ( index 0 and index 1 ) of the array



[ 9 10 11 12]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[ 1  5  9 13]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[1 2]
 [5 6]]


## Arithmetic

##### reference video :https://www.youtube.com/watch?v=VXU4LSAQDSc