# Numpy
### Used for numerical computing
Since Python is slow -> we use NumpPy, it uses C programming behind the scenes
 



In [2]:
#np is a shorter nickname for numpy
import numpy as np  
# create a python list
my_list = [1, 2, 3, 4]
print(my_list)
my_list = my_list * 2
print(my_list)
# the difference between a list and a numpy array is that the python list will repeat the list when multiplied by 2, while the numpy array will multiply each element by 2.
# create a np array 
array = np.array([1, 2, 3, 4])
print(array)
array = array * 2
print(array)







[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]
[1 2 3 4]
[2 4 6 8]


## Multidimensional arrays

In [ ]:
# 0d array, it is like a single number or point, it has no dimensions
array_0d = np.array(1)
print(array_0d.ndim)
# 1d array
array_1d = np.array([1, 2, 3, 4])
print(array_1d.ndim)
# 2d array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim)
# 3d array
array_3d = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(array_3d.ndim)    

# we need a consistent number of elements in each row to create a 2d array, 
# if we have a different number of elements in each row, we will get an error.

# previously with Python list we would access elements like this: print(my_list[0][0][0] this is called chain indexing,
# but with numpy array we can access elements like this: print(array_3d[0, 0, 0]) this is called multi-dimensional indexing that is faster than chain indexing.

# concatenating
number = array_3d[0,0,0] + array_3d[0,0,1] + array_3d[0,0,2] # 1+2+3
print(number)

0
1
2
3
6


## Slicing 

In [35]:
# 2d array

array = np.array([  [1, 2, 3, 4], 
                    [5, 6, 7, 8], 
                    [9, 10, 11, 12], 
                    [13, 14, 15, 16]])
# row selection
# array[start:end:step] , ending index is exclusive, step is optional
print(array[2]) # going to give the third row ( index 2 )
print(array[1:3]) # going to give second ( index 1 ) and third row ( index 2 )
print(array[0:]) # going to give all the rows starting from the first row ( index 0 ) to the end of the array
print(array[0:4:2]) # going to give the first and third row ( index 0 and index 2 ) because we are stepping by 2
# column selection
print(array[:, 0]) # going to give the first column ( index 0 ) of all the rows ( : )
print(array[:, 1:3]) # going to give the second and third column ( index 1 and index 2 ) of all the rows ( : )
print(array[:, 0:]) # going to give all the columns starting from the first column ( index 0 ) to the end of the array for all the rows ( : )
print(array[:, 0:4:2]) # going to give the first and third column ( index 0 and index 2 ) of all the rows ( : ) because we are stepping by 2
# subarray selection
print(array[0:2, 0:2]) # going to give the first and second row ( index 0 and index 1 ) and the first and second column ( index 0 and index 1 ) of the array



[ 9 10 11 12]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[ 1  5  9 13]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[1 2]
 [5 6]]


## Arithmetic

In [4]:
#Scalar arithmetic
array = np.array([1, 2, 3])
print(array +1 ) # going to add 1 to each element of the array
print(array - 2) # going to subtract 2 from each element of the array
print(array * 3) # going to multiply each element of the array by 3
print(array / 4) # going to divide each element of the array by 4
print(array ** 2) # going to raise each element of the array to the power of 2



[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[1 4 9]


In [5]:
#   comparison operators
scores = np.array([80, 90, 70, 60])
print(scores > 75) # going to return a boolean array where each element is True if the corresponding element in scores is greater than 75, and False otherwise
print(scores == 90) # going to return a boolean array where each element is True if the corresponding element in scores is equal to 90, and False otherwise
scores[scores > 75] # going to return the elements in scores that are greater than 75

[ True  True False False]
[False  True False False]


array([80, 90])

## Broadcasting 

In [9]:
#broadcasting is a powerful mechanism that allows numpy to perform operations on arrays of different shapes and sizes.
# it allows numpy to automatically expand the smaller array to match the shape of the larger array, so that the operation can be performed element-wise.
# for example, if we have a 2d array and a 1d array, we can add them together and numpy will automatically broadcast the 1d array to match the shape of the 2d array, so that the addition can be performed element-wise.
# example of broadcasting
array_1d = np.array([[1, 2, 3, 4]])
array_2d = np.array([[1], [2], [3], [4]])
print(array_1d.shape)
print(array_2d.shape)

print(array_1d * array_2d) # going to multiply each element of the 1d array by the corresponding element of the 2d array, and numpy will automatically broadcast the 1d array to match the shape of the 2d array, so that the multiplication can be performed element-wise.

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


## Aggregate functions

In [10]:
# aggregation functions: these are functions that take an array as input and return a single value as output, they are used to summarize the data in the array.
array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])
print(np.sum(array)) # going to return the sum of all the elements in the array
print(np.mean(array)) # going to return the mean of all the elements in the array
print(np.min(array)) # going to return the minimum value in the array
print(np.max(array)) # going to return the maximum value in the array
print(np.argmin(array)) # going to return the index of the minimum value in the array
print(np.argmax(array)) # going to return the index of the maximum value in the array

print(np.sum(array, axis=0)) # going to return the sum of each column in the array, because we are summing along the rows ( axis=0 )
print(np.sum(array, axis=1)) # going to return the sum of each row in the array, because we are summing along the columns ( axis=1 )


55
5.5
1
10
0
9
[ 7  9 11 13 15]
[15 40]


## Filtering

In [21]:
# Filtering arrays: this is the process of selecting a subset of the elements in an array based on some condition.
ages = np.array([[21,17,19,20,16,30,18,65],
                  [39,22,15,99,18,19,20,21]])

teenagers = ages[ages < 18] # going to return the elements in ages that are less than 18, boolean indexing.
print(teenagers) 
print(ages)

adults = ages[(ages >= 18) & (ages < 65)] # going to return the elements in ages that are greater than or equal to 18 and less than 65, boolean indexing with multiple conditions.
print(adults)
seniors = ages[ages >= 65]
print(seniors)
evens = ages[ ages % 2 == 0] # going to return the elements in ages that are even, boolean indexing with modulus operator.
print(evens)

# Filtering arrays with np.where() function:  preserves the shape of the original array, and it returns an array of the same shape as the original array,
# where the elements that satisfy the condition are replaced with the value specified in the second argument, and the elements that do not satisfy the condition
# are replaced with the value specified in the third argument.

adults2  = np.where(ages >= 18, ages, 0 ) # going to return an array of the same shape as ages, where the elements that are greater than or equal to 18 are replaced with their original value, and the elements that are less than 18 are replaced with 0.
print(adults2) # preserves the opriginal shape of the arraya dn any values that do noit match the condition return the value specified in the third argument ( in this case 0 ) instead of being filtered out of the array.


[17 16 15]
[[21 17 19 20 16 30 18 65]
 [39 22 15 99 18 19 20 21]]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


## Random numbers

In [34]:
# Random number generation: numpy provides a module called numpy.random, useful for generating random numbers, which can be used for various purposes such as creating random samples, shuffling data, and simulating random processes.

rng = np.random.default_rng() # going to create a random number generator object, which we can use to generate random numbers.
print(rng.integers(low = 1, high = 7, size = 2)) # going to generate a random integer between 1 (inclusive) and 7 (exclusive), which means it can generate any of the integers 1, 2, 3, 4, 5, or 6 and it will generate 2 random integers because we specified size = 2.

print(rng.integers(low = 1, high = 7, size = (3, 4))) # going to generate a 3x4 array of random integers between 1 (inclusive) and 7 (exclusive), which means it can generate any of the integers 1, 2, 3, 4, 5, or 6 and it will generate a total of 12 random integers because we specified size = (3, 4) which means we want a 3x4 array.

# seed is a value that is used to initialize the random number generator, it is used to ensure that the same sequence of random numbers is generated each time the code is run, which can be useful for debugging and reproducibility.
rng = np.random.default_rng(seed=42) # going to create a random number generator object with a seed value of 42, which means that the same sequence of random numbers will be generated each time the code is run.
print(rng.integers(low = 1, high = 7, size = (3, 4))) # going to generate the same 3x4 array of random integers between 1 (inclusive) and 7 (exclusive) each time the code is run, because we have set the seed value to 42.  

 

[6 1]
[[5 1 6 1]
 [5 1 1 6]
 [1 6 1 5]]
[[1 5 4 3]
 [3 6 1 5]
 [2 1 4 6]]


##### reference video :https://www.youtube.com/watch?v=VXU4LSAQDSc